services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO

# Si necesitas DB en dev, descomenta y ajusta.
#  db:
#    image: postgres:16
#    environment:
#      POSTGRES_USER: app
#      POSTGRES_PASSWORD: app
#      POSTGRES_DB: app
#    ports:
#      - "5432:5432"
